In [0]:
import numpy as np
np_arr=np.arange(10000)
%time z=np_arr*2

CPU times: user 693 µs, sys: 167 µs, total: 860 µs
Wall time: 748 µs


In [0]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [0]:
reg_arr=range(10000)
%time y=[i*2 for i in reg_arr]

CPU times: user 796 µs, sys: 0 ns, total: 796 µs
Wall time: 801 µs


In [0]:
ndarry=np.random.rand(3,3)
print(ndarry)
print(ndarry.ndim)
print(ndarry.shape)
print(ndarry.dtype)

[[0.40383416 0.64393911 0.73776735]
 [0.78528502 0.86087202 0.23673988]
 [0.09212743 0.69511155 0.09741757]]
2
(3, 3)
float64


In [0]:
np.ones(3,dtype=np.int16)
np.ones((3,3),dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [0]:
np.zeros(3,dtype=np.int16)
np.zeros((3,3),dtype=np.int16)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [0]:
np.full((3,3),6)


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [0]:
print(np.ones_like(ndarry))
print()
print(np.ones(ndarry.shape))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
np.random.seed(4)#fix the random number every time
np.random.randn(3,5)

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152],
       [-1.58457724, -0.64770677,  0.59857517,  0.33225003, -1.14747663],
       [ 0.61866969, -0.08798693,  0.4250724 ,  0.33225315, -1.15681626]])

In [0]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))

print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

print(np.dot(a,b))

print(np.linalg.det(a))

print(np.linalg.inv(a))

[[7 1 4]
 [5 9 7]
 [4 8 4]]
[[2 5 9]
 [4 1 3]
 [5 7 2]]
[[ 9  6 13]
 [ 9 10 10]
 [ 9 15  6]]
[[ 5 -4 -5]
 [ 1  8  4]
 [-1  1  2]]
[[14  5 36]
 [20  9 21]
 [20 56  8]]
[[3.5        0.2        0.44444444]
 [1.25       9.         2.33333333]
 [0.8        1.14285714 2.        ]]
[[38 64 74]
 [81 83 86]
 [60 56 68]]
-115.99999999999999
[[ 0.17241379 -0.24137931  0.25      ]
 [-0.06896552 -0.10344828  0.25      ]
 [-0.03448276  0.44827586 -0.5       ]]


In [0]:
a>3

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [0]:
a==b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
z=np.arange(10)
z[2:4]=100
print(z)
z[:]=200
print(z)

z=np.arange(10)
y=z.copy()

z[:]=20
print(z)
print(y)

[  0   1 100 100   4   5   6   7   8   9]
[200 200 200 200 200 200 200 200 200 200]
[20 20 20 20 20 20 20 20 20 20]
[0 1 2 3 4 5 6 7 8 9]


In [0]:
a=np.random.randint(1,10,(3,3,3))
print(a)

[[[4 9 6]
  [2 6 5]
  [4 6 7]]

 [[7 2 1]
  [6 3 1]
  [6 9 6]]

 [[8 9 1]
  [4 8 1]
  [5 8 8]]]


In [0]:
z=np.random.randn(10,3)
print(z)
print(z.sum(axis=1))
print(z.sum(axis=1)>0)
print(z[z.sum(axis=1)>0])



[[ 0.18614784 -0.62383863  1.04835921]
 [ 0.34927263 -0.64792707 -0.46978077]
 [ 0.01480992  1.52023325  0.3612511 ]
 [ 0.06559625 -0.1952047  -0.40782776]
 [-1.57437038  0.0587733  -0.78021358]
 [-0.16304883  0.3665794  -0.01326179]
 [ 0.66476937  0.74528601  0.52752625]
 [ 0.26302095 -0.25727904 -1.6417257 ]
 [-0.64924401  1.11608981  0.1931333 ]
 [-0.7819294  -0.12376487 -1.00802767]]
[ 0.61066842 -0.76843521  1.89629427 -0.5374362  -2.29581066  0.19026878
  1.93758163 -1.63598379  0.6599791  -1.91372194]
[ True False  True False False  True  True False  True False]
[[ 0.18614784 -0.62383863  1.04835921]
 [ 0.01480992  1.52023325  0.3612511 ]
 [-0.16304883  0.3665794  -0.01326179]
 [ 0.66476937  0.74528601  0.52752625]
 [-0.64924401  1.11608981  0.1931333 ]]


In [0]:
z[z<0]=0
print(z)

[[0.18614784 0.         1.04835921]
 [0.34927263 0.         0.        ]
 [0.01480992 1.52023325 0.3612511 ]
 [0.06559625 0.         0.        ]
 [0.         0.0587733  0.        ]
 [0.         0.3665794  0.        ]
 [0.66476937 0.74528601 0.52752625]
 [0.26302095 0.         0.        ]
 [0.         1.11608981 0.1931333 ]
 [0.         0.         0.        ]]


In [0]:
mask=(z>0)&(z<0.5)
z[mask]
print(z)

print(z[[1,2,3],[0,0,0]])

[[0.18614784 0.         1.04835921]
 [0.34927263 0.         0.        ]
 [0.01480992 1.52023325 0.3612511 ]
 [0.06559625 0.         0.        ]
 [0.         0.0587733  0.        ]
 [0.         0.3665794  0.        ]
 [0.66476937 0.74528601 0.52752625]
 [0.26302095 0.         0.        ]
 [0.         1.11608981 0.1931333 ]
 [0.         0.         0.        ]]
[0.34927263 0.01480992 0.06559625]


In [0]:
#create 8 x 8 x 8

met=np.random.randint(1,10,(8,8,8))
mask=(met>3) & (met<8)
met[mask]=-1*met[mask]

print(met)

[[[-6 -7  8 -4 -4 -4  2 -5]
  [-6  3 -4  3 -7 -4 -7 -7]
  [ 9  3  8 -7  2 -6 -6  3]
  [ 9 -6  2  3 -4  2 -7  2]
  [ 3  3  1 -5  8  1  1 -5]
  [-4  2 -7  2  9 -4  2 -4]
  [ 9 -7 -6  1 -7 -6 -7  2]
  [ 3  2 -5  1 -6  3 -4  3]]

 [[-7 -4  9 -6 -4  2  9  2]
  [-5 -4  1  3  1  3  1 -5]
  [-7 -4  9 -5  1  9 -6 -6]
  [-4  8 -7 -6  9  8 -6  3]
  [ 1  8  8  2 -5  1 -7 -7]
  [ 2  8 -4  1  3  9 -6 -4]
  [-7  1 -4  2 -4  1 -5  9]
  [ 1  8  9  8  9 -7  1 -5]]

 [[ 3 -5  1 -7 -5  1  8  9]
  [ 8 -5  8  9  1 -5  9 -4]
  [ 1 -6  8  8 -4  8  3 -4]
  [-7 -6  1  3 -4  8 -5 -5]
  [-4 -6 -5 -7  3 -5  3 -6]
  [ 9 -6  9  8  3 -7 -5  2]
  [ 8  1  3  9  1  9  8  9]
  [ 3  9 -6 -6 -5  2  3  3]]

 [[-7 -5  3  3 -6  3  3  1]
  [-7 -7 -7  9  1  9  9  2]
  [ 9 -7  1  8  1 -4  8 -5]
  [ 1  9 -7  3  9 -6 -7 -5]
  [-6  9  8  2 -5  3  8 -5]
  [ 2  2  3 -5  9  8 -6  1]
  [ 2  3  8  9  3  1  3 -6]
  [ 9  3  2  2  3  3 -6  3]]

 [[-5  9  2  9 -4 -4 -5 -4]
  [-4 -5 -6 -5 -7  2  1  2]
  [ 8  1  9 -7  1 -7  3 -6]
  [-6  8 -4 

In [0]:
#mul 8x3 and 3x2
a=np.random.randint(1,10,(8,3))
b=np.random.randint(1,10,(3,2))

nresult=np.dot(a,b)
print(nresult[:,0])
print(nresult[:,1])
p.T[0]#transpose

[53 47 42 82 89 37 88 89]
[76 41 78 84 77 30 90 96]


In [0]:
z=np.arange(100)
print(z)
print(z.reshape((10,10)))
print(z.reshape((5,4,5)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [0]:
np.sqrt(z)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [0]:
np.add(z,z)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [0]:
z*5

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495])

In [0]:
rem,whole_part=np.modf(z)
print(rem)
print(whole_part)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [0]:
p=[]
np.sqrt(z,z)

TypeError: ignored

In [0]:
# closest to origin

coordinates = np.random.randn(100, 2)
dist=[]
for coordinate in coordinates:
  res=np.sqrt(coordinate[0]**2+coordinate[1]**2)
  dist.extend([res])

top_10=np.sort(dist)[:10]
#print(top_10)
for cor in top_10:
  print(coordinates[dist.index(cor),:])

[0.05459946 0.03105443]
[ 0.01304706 -0.1378239 ]
[-0.38731467  0.15845449]
[-0.0351381   0.43605096]
[ 0.39970436 -0.18575169]
[-0.31044823 -0.43167313]
[0.34117187 0.43169496]
[-0.62860659  0.02008215]
[-6.14542467e-04 -6.32854932e-01]
[ 0.36166696 -0.57272792]


In [0]:
# circle redius

coordinates = np.random.randn(100, 2)
dist=[]
for coordinate in coordinates:
  res=np.sqrt(coordinate[0]**2+coordinate[1]**2)
  dist.extend([res])

radius_circle=int(input('enter the raduis of circle'))
for distance in dist:
  if distance<radius_circle:
    print(coordinates[dist.index(distance),:])

In [0]:
# calculte the pi

inside_circle = 0
total_points = 10000000

for i in range(0, total_points):
  x = np.random.uniform(-1,1)
  y = np.random.uniform(-1,1)
  if np.sqrt(x**2 + y**2) < 1.0:
      inside_circle += 1
pi = (float(inside_circle) / total_points) * 4
print(pi)

3.140712


In [0]:
# calculte the pi short code

total_points = 10000000
x = np.random.uniform(-1,1,total_points)
y = np.random.uniform(-1,1,total_points)
new=np.sqrt(np.add(x**2 , y**2))
inside=new[new<1.0].shape

pi = (float(inside[0]) / total_points) * 4
print(pi)

3.1422132


In [0]:
points=np.random.randn(100,2)
d_origin=np.sqrt(np.sum(points*points,axis=1))
d_origin.argsort()
print(points[d_origin.argsort()][:10])

In [0]:
po=np.random.randint(2,10,(10,2))
print(po)
print(np.sum(po*po,axis=0))


[[5 8]
 [6 6]
 [9 2]
 [3 3]
 [7 8]
 [4 7]
 [8 5]
 [2 6]
 [7 2]
 [8 5]]
[397 316]


In [0]:
#create 8 x 8 x 8

met=np.random.randint(5,9,(8,8,8))


print(met)

In [0]:
a=np.random.randint(5,9,(5,5))
b=np.random.randint(5,9,(5,5))
c=np.dot(a,b)

res=np.diag(c)
print(res)


[224 205 177 204 259]


In [0]:
met=np.random.randn(1,10)
print(met)
mask=met>0
print()
mask1=met>0
print(mask1)
mask1=~mask1
print(mask1)
print()

print(~(met>0))
met[~(met>0)]
print(met)

np.logical_not(mask)
np.logical_not(mask,mask)
np.invert(mask)



In [0]:
arr=np.random.randn(4,4)

np.where(arr>0,arr,-2)

np.where(arr>0,2,-2)

array([[ 2, -2,  2, -2],
       [ 2,  2, -2, -2],
       [-2, -2,  2, -2],
       [-2,  2, -2, -2]])

In [0]:
import numpy as np
z=np.random.randint(0,100,20)
print((z>50).sum())
print((z>50).any())
print((z>50).all())


7
True
False


In [0]:
import pandas as pd
#p
z=pd.Series([1,2,3,4],index=['a','b','c','d'])


In [183]:
pd.Series([1,2,3])


0    1
1    2
2    3
dtype: int64

In [184]:
pd.Series([1,2,3])+pd.Series([3,4],index=[2,3])

0    NaN
1    NaN
2    6.0
3    NaN
dtype: float64

In [186]:
z=pd.Series([1,2,3,4],index=['a','b','c','d'])
z*2
np.exp(z)

a     2.718282
b     7.389056
c    20.085537
d    54.598150
dtype: float64

In [187]:
z = pd.Series({
    'x':1,
    'b':2,
    'y':3,
    'd':4
    },
    index=['b','x','d','f'])
print(z)

b    2.0
x    1.0
d    4.0
f    NaN
dtype: float64


In [189]:

# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [191]:

frame=pd.DataFrame({'pop':{'UP':1000,'KA':500,'DL':200},'income':{'UP':100,'KA':70,'DL':50}})
frame

pop  income
DL   200      50
KA   500      70
UP  1000     100

In [193]:
frame['income_cat']=pd.Series(['low','medium','high'],index=['DL','KA','UP'])
frame

pop  income income_cat
DL   200      50        low
KA   500      70     medium
UP  1000     100       high

In [197]:
del frame['income_cat']

frame.values

KeyError: ignored

In [0]:
data=[
    {'fname':'Megha','lname':'gupta','Age':10},
    {'fname':'Shikha','lname':'Gautam'}
]

In [206]:
z=pd.DataFrame(data)
z['Age']

0    10.0
1     NaN
Name: Age, dtype: float64

In [0]:
#users=pd.read_csv('https://bit.ly/2JIORnq',sep='|',index_col='user_id')
users=pd.read_csv('https://bit.ly/2JIORnq',sep='|')
df = pd.DataFrame(users)
df.describe()

a=users['age'].value_counts()

oc=users['occupation'].value_counts().head(10)


#df.index.user_id


In [228]:
a.iloc[-1]

1